<?php

echo 'test';

########################################################################
# Extension Manager/Repository config file for ext: "web_model_import"
#
# Auto generated by Extension Builder 2013-01-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Import Model',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Philipp Buss',
	'author_email' => 'buss@typo3-hamburg-berlin.de',
	'author_company' => 'Typo3 Hamburg Berlin',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>